// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy1OuY0kA9qDC3l6oeashm2Ejs9OcNMFw',
    appId: '1:778626792345:web:667df293c817ad4521b108',
    messagingSenderId: '778626792345',
    projectId: 'benroseclub',
    authDomain: 'benroseclub.firebaseapp.com',
    storageBucket: 'benroseclub.firebasestorage.app',
    measurementId: 'G-H69N1FC4LS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVxn2ckxUDx0AEBdazx34i8bEdzvfiV1I',
    appId: '1:778626792345:android:ab1a070a619992f221b108',
    messagingSenderId: '778626792345',
    projectId: 'benroseclub',
    storageBucket: 'benroseclub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH6vh-kAQHeYUQjovXG4oynWUmjfucJss',
    appId: '1:778626792345:ios:d405f75519b17cf221b108',
    messagingSenderId: '778626792345',
    projectId: 'benroseclub',
    storageBucket: 'benroseclub.firebasestorage.app',
    iosBundleId: 'io.github.ianshaloom.benroseclub',
  );

}